"""add agent jobs table

Revision ID: 1e756bb6d1f7
Revises: c5b27f3e274a
Create Date: 2025-12-03 20:14:39.656688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e756bb6d1f7'
down_revision: Union[str, Sequence[str], None] = 'c5b27f3e274a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('user_cred', sa.JSON(), nullable=False),
    sa.Column('signin_url', sa.String(), nullable=False),
    sa.Column('billing_history_url', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['user_billing_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_jobs_status', 'agent_jobs', ['status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_jobs_status', table_name='agent_jobs')
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###
