"""add_portal_configs_table

Revision ID: 2fc1ea109df9
Revises: 4e850865e33b
Create Date: 2025-08-25 23:58:39.577886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc1ea109df9'
down_revision: Union[str, Sequence[str], None] = '4e850865e33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login_url', sa.String(), nullable=False),
    sa.Column('billing_url', sa.String(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portal_configs')
    # ### end Alembic commands ###
