"""rename_portal_configs_to_providers

Revision ID: 4d4f4b4c632c
Revises: 2fc1ea109df9
Create Date: 2025-08-26 00:01:53.625913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d4f4b4c632c'
down_revision: Union[str, Sequence[str], None] = '2fc1ea109df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login_url', sa.String(), nullable=False),
    sa.Column('billing_url', sa.String(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('portal_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_configs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('login_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('billing_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extras', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('portal_configs_pkey'))
    )
    op.drop_table('providers')
    # ### end Alembic commands ###
