"""add_is_eligible_for_retry_to_user_billing_credentials

Revision ID: 827ec51da280
Revises: c074085b83cb
Create Date: 2025-09-10 14:11:50.757645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827ec51da280'
down_revision: Union[str, Sequence[str], None] = 'c074085b83cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_billing_credentials', sa.Column('is_eligible_for_retry', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_billing_credentials', 'is_eligible_for_retry')
    # ### end Alembic commands ###
