"""add_excel_and_json_blob_urls_to_billing_results

Revision ID: c074085b83cb
Revises: 4d4f4b4c632c
Create Date: 2025-09-09 13:02:49.356089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c074085b83cb'
down_revision: Union[str, Sequence[str], None] = '4d4f4b4c632c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_results', sa.Column('excel_blob_url', sa.String(), nullable=True))
    op.add_column('billing_results', sa.Column('json_blob_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_results', 'json_blob_url')
    op.drop_column('billing_results', 'excel_blob_url')
    # ### end Alembic commands ###
