"""add is_active to user_billing_credentials

Revision ID: c5b27f3e274a
Revises: f6c376d7ec61
Create Date: 2025-11-18 13:25:03.472795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b27f3e274a'
down_revision: Union[str, Sequence[str], None] = 'f6c376d7ec61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_billing_credentials', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_billing_credentials', 'is_active')
    # ### end Alembic commands ###
