"""add agent jobs table

Revision ID: eb7410e6d99d
Revises: 7e010ad503c7
Create Date: 2025-12-04 18:14:30.739850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7410e6d99d'
down_revision: Union[str, Sequence[str], None] = '7e010ad503c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('user_cred', sa.JSON(), nullable=False),
    sa.Column('signin_url', sa.String(), nullable=False),
    sa.Column('billing_history_url', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['user_billing_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_jobs_logs')
    # ### end Alembic commands ###
